### ISSUE TITLE
signature of main vs SDLmain

### ISSUE THREAD

**Issue by ClnViewer** [Noah11012/sdl2-tutorial-code#1]
Great examples! and well-designed article, read with pleasure.
But, you simply declare the signature of the main() function.

This causes an error:

```
libSDL2main.a(SDL_windows_main.o): In function 'main_getcmdline':
/Users/valve/release/SDL/SDL2-2.0.9-source/foo-x86/../src/main/windows/SDL_windows_main.c:175: 

undefined reference to 'SDL_main'

```

Needed full signature:

```
int main(int argc, char * argv[])
```
please, correct examples.

**Comment by Noah11012** [comment]
Sorry that it took this long to fix this issue but I never saw this issue because I never check my notifications.
